# Generated by Django 5.1.3 on 2024-11-29 13:06

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[products.models.validate_image]),
        ),
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
    ]
